SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE cart;
SET FOREIGN_KEY_CHECKS = 1;
INSERT INTO cart (id, member_id) VALUES (1, 1);
INSERT INTO cart (id, member_id) VALUES (2, 2);
INSERT INTO cart (id, member_id) VALUES (3, 3);
INSERT INTO cart (id, member_id) VALUES (4, 4);
INSERT INTO cart (id, member_id) VALUES (5, 5);
INSERT INTO cart (id, member_id) VALUES (6, 6);
INSERT INTO cart (id, member_id) VALUES (7, 7);
INSERT INTO cart (id, member_id) VALUES (8, 8);
INSERT INTO cart (id, member_id) VALUES (9, 9);
INSERT INTO cart (id, member_id) VALUES (10, 10);
INSERT INTO cart (id, member_id) VALUES (11, 11);
INSERT INTO cart (id, member_id) VALUES (12, 12);